[project]
name = "napari_psf_analysis"
description = "Napari plugin to analyze point spread functions (PSFs)."
readme = "README.md"
requires-python = ">=3.9"
license = "BSD-3-Clause"
authors = [
  { name = "Tim-Oliver Buchholz", email = "tim-oliver.buchholz@fmi.ch" },
  { name = "Jan Eglinger", email = "jan.eglinger@fmi.ch" },
]
keywords = []
classifiers = [
  "Development Status :: 4 - Beta",
  "Framework :: napari",
  "License :: OSI Approved :: BSD License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]
dependencies = [
  "matplotlib>=3.1,<3.9",
  "matplotlib-scalebar>=0.9.0,<0.10",
  "napari>=0.7.0,<0.8",
  "numpy",
  "scikit-image",
]
dynamic = ["version"]

[project.urls]
Documentation = "https://github.com/fmi-faim/napari-psf-analysis#readme"
Issues = "https://github.com/fmi-faim/napari-psf-analysis/issues"
Source = "https://github.com/fmi-faim/napari-psf-analysis"

[project.entry-points."napari.manifest"]
napari_psf_analysis = "napari_psf_analysis:napari.yaml"

[build-system]
requires = ["hatch-vcs", "hatchling"]
build-backend = "hatchling.build"

[tool.coverage.run]
source_pkgs = ["napari_psf_analysis", "tests"]
branch = true
parallel = true
omit = []

[tool.coverage.paths]
napari_psf_analysis = [
  "src/napari_psf_analysis",
  "*/napari-psf-analysis/src/napari_psf_analysis"
]
tests = ["tests", "*/napari-psf-analysis/tests"]

[tool.coverage.report]
show_missing = true
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

[tool.hatch.version]
source = "vcs"

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["win-64", "osx-arm64", "linux-64"]

[tool.pixi.pypi-dependencies]
napari-psf-analysis = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
napari = ">=0.7.0,<0.8"

[dependency-groups]
lint = ["mypy", "ruff"]
test = ["pytest", "pytest-cov", "pytest-qt", "pyqt6"]

[tool.pixi.feature.lint.tasks]
check = "mypy --install-types --non-interactive src tests"

[tool.pixi.feature.test.tasks]
test = "pytest --cov=src --cov-report term-missing"
cov-xml = "pytest --cov=src --cov-report xml"

[tool.pixi.environments]
default = { solve-group = "py311" }
docs = { features = ["docs"], no-default-feature = true }
py310 = { features = ["py310", "test"], solve-group = "py310" }
py311 = { features = ["py311", "test"], solve-group = "py311" }
py312 = { features = ["py312", "test"], solve-group = "py312" }
py313 = { features = ["py313", "test"], solve-group = "py313" }
# py314 = { features = ["py314", "test"], solve-group = "py314" }
lint = { features = ["lint"], solve-group = "py311" }
build = { features = ["build"], no-default-feature = true }

[tool.pixi.feature.build.dependencies]
hatch = ">=1.16.3,<2"

[tool.pixi.feature.build.tasks]
build = "hatch build"

[tool.pixi.feature.py310.dependencies]
python = "3.10.*"

[tool.pixi.feature.py311.dependencies]
python = "3.11.*"

[tool.pixi.feature.py312.dependencies]
python = "3.12.*"

[tool.pixi.feature.py313.dependencies]
python = "3.13.*"

[tool.pixi.feature.docs.dependencies]
sphinx = ">=9.1.0,<10"
myst-parser = ">=5.0.0,<6"
sphinx-inline-tabs = ">=2025.12.21.14,<2026"
sphinx-copybutton = ">=0.5.2,<0.6"
furo = ">=2025.12.19,<2026"

# [tool.pixi.feature.py314.dependencies]
# python = "3.14.*"

[tool.pytest.ini_options]
addopts = [
  "--import-mode=importlib",
]

[tool.ruff]
target-version = "py310"
line-length = 88

[tool.ruff.lint.extend-per-file-ignores]
"**/tests/*" = ["INP001"]
